import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { AppSidebar } from '@components/components/app-sidebar';
import { SiteHeader } from '@components/components/site-header';
import { SidebarInset, SidebarProvider } from '@components/components/ui/sidebar';
import { Toaster } from '@components/components/ui/sonner';
import { StoreProvider } from '@components/store/StoreProvider';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <StoreProvider>
          <SidebarProvider>
            <AppSidebar variant="inset" />
            <SidebarInset>
              <SiteHeader />

              <div className="flex flex-1 flex-col gap-2 p-4 @container/main lg:p-6">
                {children}
              </div>
            </SidebarInset>
          </SidebarProvider>
          <Toaster />
        </StoreProvider>
      </body>
    </html>
  );
}
